//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParKing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarParKingDBEntities : DbContext
    {
        public CarParKingDBEntities()
            : base("name=CarParKingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parkplatzdetails> Parkplatzdetails { get; set; }
        public virtual DbSet<Parkplatzübersicht> Parkplatzübersicht { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
