//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParKing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parkplatzdetails
    {
        public long ParkplatzdetailD { get; set; }
        public long ParkplatzübersichtID { get; set; }
        public long AnzahlParkplätze { get; set; }
    
        public virtual Parkplatzübersicht Parkplatzübersicht { get; set; }
    }
}
