//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParKing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parkplatzübersicht
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parkplatzübersicht()
        {
            this.Parkplatzdetails = new HashSet<Parkplatzdetails>();
        }
    
        public long ParkplatzübersichtID { get; set; }
        public string ParkplatzName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parkplatzdetails> Parkplatzdetails { get; set; }
    }
}
