//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParKing.CarParKingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.demo.fhsalzburg.ac.at/", ConfigurationName="CarParKingService.NewWebService")]
    public interface NewWebService {
        
        // CODEGEN: Parameter "name" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.demo.fhsalzburg.ac.at/NewWebService/savePersonRequest", ReplyAction="http://webservice.demo.fhsalzburg.ac.at/NewWebService/savePersonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarParKing.CarParKingService.savePersonResponse savePerson(CarParKing.CarParKingService.savePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.demo.fhsalzburg.ac.at/NewWebService/savePersonRequest", ReplyAction="http://webservice.demo.fhsalzburg.ac.at/NewWebService/savePersonResponse")]
        System.Threading.Tasks.Task<CarParKing.CarParKingService.savePersonResponse> savePersonAsync(CarParKing.CarParKingService.savePersonRequest request);
        
        // CODEGEN: Parameter "return" erfordert zusätzliche Schemainformationen, die nicht mit dem Parametermodus erfasst werden können. Das spezifische Attribut ist "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.demo.fhsalzburg.ac.at/NewWebService/getPersonListRequest", ReplyAction="http://webservice.demo.fhsalzburg.ac.at/NewWebService/getPersonListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.CarParKingService.getPersonListResponse getPersonList(CarParKing.CarParKingService.getPersonListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.demo.fhsalzburg.ac.at/NewWebService/getPersonListRequest", ReplyAction="http://webservice.demo.fhsalzburg.ac.at/NewWebService/getPersonListResponse")]
        System.Threading.Tasks.Task<CarParKing.CarParKingService.getPersonListResponse> getPersonListAsync(CarParKing.CarParKingService.getPersonListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.demo.fhsalzburg.ac.at/")]
    public partial class person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="savePerson", WrapperNamespace="http://webservice.demo.fhsalzburg.ac.at/", IsWrapped=true)]
    public partial class savePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.demo.fhsalzburg.ac.at/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.CarParKingService.person name;
        
        public savePersonRequest() {
        }
        
        public savePersonRequest(CarParKing.CarParKingService.person name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="savePersonResponse", WrapperNamespace="http://webservice.demo.fhsalzburg.ac.at/", IsWrapped=true)]
    public partial class savePersonResponse {
        
        public savePersonResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonList", WrapperNamespace="http://webservice.demo.fhsalzburg.ac.at/", IsWrapped=true)]
    public partial class getPersonListRequest {
        
        public getPersonListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPersonListResponse", WrapperNamespace="http://webservice.demo.fhsalzburg.ac.at/", IsWrapped=true)]
    public partial class getPersonListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.demo.fhsalzburg.ac.at/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.CarParKingService.person[] @return;
        
        public getPersonListResponse() {
        }
        
        public getPersonListResponse(CarParKing.CarParKingService.person[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewWebServiceChannel : CarParKing.CarParKingService.NewWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewWebServiceClient : System.ServiceModel.ClientBase<CarParKing.CarParKingService.NewWebService>, CarParKing.CarParKingService.NewWebService {
        
        public NewWebServiceClient() {
        }
        
        public NewWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.CarParKingService.savePersonResponse CarParKing.CarParKingService.NewWebService.savePerson(CarParKing.CarParKingService.savePersonRequest request) {
            return base.Channel.savePerson(request);
        }
        
        public void savePerson(CarParKing.CarParKingService.person name) {
            CarParKing.CarParKingService.savePersonRequest inValue = new CarParKing.CarParKingService.savePersonRequest();
            inValue.name = name;
            CarParKing.CarParKingService.savePersonResponse retVal = ((CarParKing.CarParKingService.NewWebService)(this)).savePerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.CarParKingService.savePersonResponse> CarParKing.CarParKingService.NewWebService.savePersonAsync(CarParKing.CarParKingService.savePersonRequest request) {
            return base.Channel.savePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.CarParKingService.savePersonResponse> savePersonAsync(CarParKing.CarParKingService.person name) {
            CarParKing.CarParKingService.savePersonRequest inValue = new CarParKing.CarParKingService.savePersonRequest();
            inValue.name = name;
            return ((CarParKing.CarParKingService.NewWebService)(this)).savePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.CarParKingService.getPersonListResponse CarParKing.CarParKingService.NewWebService.getPersonList(CarParKing.CarParKingService.getPersonListRequest request) {
            return base.Channel.getPersonList(request);
        }
        
        public CarParKing.CarParKingService.person[] getPersonList() {
            CarParKing.CarParKingService.getPersonListRequest inValue = new CarParKing.CarParKingService.getPersonListRequest();
            CarParKing.CarParKingService.getPersonListResponse retVal = ((CarParKing.CarParKingService.NewWebService)(this)).getPersonList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.CarParKingService.getPersonListResponse> CarParKing.CarParKingService.NewWebService.getPersonListAsync(CarParKing.CarParKingService.getPersonListRequest request) {
            return base.Channel.getPersonListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.CarParKingService.getPersonListResponse> getPersonListAsync() {
            CarParKing.CarParKingService.getPersonListRequest inValue = new CarParKing.CarParKingService.getPersonListRequest();
            return ((CarParKing.CarParKingService.NewWebService)(this)).getPersonListAsync(inValue);
        }
    }
}
