//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParKing.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="ServiceReference1.Parking")]
    public interface Parking {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/editParkingPlaceRequest", ReplyAction="http://service/Parking/editParkingPlaceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.editParkingPlaceResponse editParkingPlace(CarParKing.ServiceReference1.editParkingPlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/editParkingPlaceRequest", ReplyAction="http://service/Parking/editParkingPlaceResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.editParkingPlaceResponse> editParkingPlaceAsync(CarParKing.ServiceReference1.editParkingPlaceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getTicketListRequest", ReplyAction="http://service/Parking/getTicketListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.getTicketListResponse getTicketList(CarParKing.ServiceReference1.getTicketListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getTicketListRequest", ReplyAction="http://service/Parking/getTicketListResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getTicketListResponse> getTicketListAsync(CarParKing.ServiceReference1.getTicketListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/editTicketRequest", ReplyAction="http://service/Parking/editTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.editTicketResponse editTicket(CarParKing.ServiceReference1.editTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/editTicketRequest", ReplyAction="http://service/Parking/editTicketResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.editTicketResponse> editTicketAsync(CarParKing.ServiceReference1.editTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/createTicketRequest", ReplyAction="http://service/Parking/createTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.createTicketResponse createTicket(CarParKing.ServiceReference1.createTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/createTicketRequest", ReplyAction="http://service/Parking/createTicketResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.createTicketResponse> createTicketAsync(CarParKing.ServiceReference1.createTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getActiveTicketListRequest", ReplyAction="http://service/Parking/getActiveTicketListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.getActiveTicketListResponse getActiveTicketList(CarParKing.ServiceReference1.getActiveTicketListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getActiveTicketListRequest", ReplyAction="http://service/Parking/getActiveTicketListResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getActiveTicketListResponse> getActiveTicketListAsync(CarParKing.ServiceReference1.getActiveTicketListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getParkingPlaceByIdRequest", ReplyAction="http://service/Parking/getParkingPlaceByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.getParkingPlaceByIdResponse getParkingPlaceById(CarParKing.ServiceReference1.getParkingPlaceByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getParkingPlaceByIdRequest", ReplyAction="http://service/Parking/getParkingPlaceByIdResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getParkingPlaceByIdResponse> getParkingPlaceByIdAsync(CarParKing.ServiceReference1.getParkingPlaceByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getParkingPlaceListRequest", ReplyAction="http://service/Parking/getParkingPlaceListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.getParkingPlaceListResponse getParkingPlaceList(CarParKing.ServiceReference1.getParkingPlaceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getParkingPlaceListRequest", ReplyAction="http://service/Parking/getParkingPlaceListResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getParkingPlaceListResponse> getParkingPlaceListAsync(CarParKing.ServiceReference1.getParkingPlaceListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/createParkingPlaceRequest", ReplyAction="http://service/Parking/createParkingPlaceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.createParkingPlaceResponse createParkingPlace(CarParKing.ServiceReference1.createParkingPlaceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/createParkingPlaceRequest", ReplyAction="http://service/Parking/createParkingPlaceResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.createParkingPlaceResponse> createParkingPlaceAsync(CarParKing.ServiceReference1.createParkingPlaceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getInactiveTicketListRequest", ReplyAction="http://service/Parking/getInactiveTicketListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarParKing.ServiceReference1.getInactiveTicketListResponse getInactiveTicketList(CarParKing.ServiceReference1.getInactiveTicketListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Parking/getInactiveTicketListRequest", ReplyAction="http://service/Parking/getInactiveTicketListResponse")]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getInactiveTicketListResponse> getInactiveTicketListAsync(CarParKing.ServiceReference1.getInactiveTicketListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class parkingPlace : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int deletedField;
        
        private int idField;
        
        private string nameField;
        
        private int numberOfParkingSlotsField;
        
        private double pricePerHourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numberOfParkingSlots {
            get {
                return this.numberOfParkingSlotsField;
            }
            set {
                this.numberOfParkingSlotsField = value;
                this.RaisePropertyChanged("numberOfParkingSlots");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double pricePerHour {
            get {
                return this.pricePerHourField;
            }
            set {
                this.pricePerHourField = value;
                this.RaisePropertyChanged("pricePerHour");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class ticket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int deletedField;
        
        private string entrytimeField;
        
        private string exittimeField;
        
        private int paidField;
        
        private double priceField;
        
        private int ticketnumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string entrytime {
            get {
                return this.entrytimeField;
            }
            set {
                this.entrytimeField = value;
                this.RaisePropertyChanged("entrytime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string exittime {
            get {
                return this.exittimeField;
            }
            set {
                this.exittimeField = value;
                this.RaisePropertyChanged("exittime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int paid {
            get {
                return this.paidField;
            }
            set {
                this.paidField = value;
                this.RaisePropertyChanged("paid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ticketnumber {
            get {
                return this.ticketnumberField;
            }
            set {
                this.ticketnumberField = value;
                this.RaisePropertyChanged("ticketnumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editParkingPlace", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editParkingPlaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.parkingPlace arg0;
        
        public editParkingPlaceRequest() {
        }
        
        public editParkingPlaceRequest(CarParKing.ServiceReference1.parkingPlace arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editParkingPlaceResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editParkingPlaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public editParkingPlaceResponse() {
        }
        
        public editParkingPlaceResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicketList", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getTicketListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getTicketListRequest() {
        }
        
        public getTicketListRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicketListResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getTicketListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.ticket[] @return;
        
        public getTicketListResponse() {
        }
        
        public getTicketListResponse(CarParKing.ServiceReference1.ticket[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editTicket", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.ticket arg1;
        
        public editTicketRequest() {
        }
        
        public editTicketRequest(int arg0, CarParKing.ServiceReference1.ticket arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editTicketResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class editTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public editTicketResponse() {
        }
        
        public editTicketResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTicket", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.ticket arg1;
        
        public createTicketRequest() {
        }
        
        public createTicketRequest(int arg0, CarParKing.ServiceReference1.ticket arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTicketResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public createTicketResponse() {
        }
        
        public createTicketResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getActiveTicketList", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getActiveTicketListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getActiveTicketListRequest() {
        }
        
        public getActiveTicketListRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getActiveTicketListResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getActiveTicketListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.ticket[] @return;
        
        public getActiveTicketListResponse() {
        }
        
        public getActiveTicketListResponse(CarParKing.ServiceReference1.ticket[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParkingPlaceById", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getParkingPlaceByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getParkingPlaceByIdRequest() {
        }
        
        public getParkingPlaceByIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParkingPlaceByIdResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getParkingPlaceByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.parkingPlace @return;
        
        public getParkingPlaceByIdResponse() {
        }
        
        public getParkingPlaceByIdResponse(CarParKing.ServiceReference1.parkingPlace @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParkingPlaceList", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getParkingPlaceListRequest {
        
        public getParkingPlaceListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getParkingPlaceListResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getParkingPlaceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.parkingPlace[] @return;
        
        public getParkingPlaceListResponse() {
        }
        
        public getParkingPlaceListResponse(CarParKing.ServiceReference1.parkingPlace[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createParkingPlace", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createParkingPlaceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.parkingPlace arg0;
        
        public createParkingPlaceRequest() {
        }
        
        public createParkingPlaceRequest(CarParKing.ServiceReference1.parkingPlace arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createParkingPlaceResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class createParkingPlaceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public createParkingPlaceResponse() {
        }
        
        public createParkingPlaceResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInactiveTicketList", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getInactiveTicketListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getInactiveTicketListRequest() {
        }
        
        public getInactiveTicketListRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInactiveTicketListResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getInactiveTicketListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarParKing.ServiceReference1.ticket[] @return;
        
        public getInactiveTicketListResponse() {
        }
        
        public getInactiveTicketListResponse(CarParKing.ServiceReference1.ticket[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParkingChannel : CarParKing.ServiceReference1.Parking, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParkingClient : System.ServiceModel.ClientBase<CarParKing.ServiceReference1.Parking>, CarParKing.ServiceReference1.Parking {
        
        public ParkingClient() {
        }
        
        public ParkingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParkingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.editParkingPlaceResponse CarParKing.ServiceReference1.Parking.editParkingPlace(CarParKing.ServiceReference1.editParkingPlaceRequest request) {
            return base.Channel.editParkingPlace(request);
        }
        
        public int editParkingPlace(CarParKing.ServiceReference1.parkingPlace arg0) {
            CarParKing.ServiceReference1.editParkingPlaceRequest inValue = new CarParKing.ServiceReference1.editParkingPlaceRequest();
            inValue.arg0 = arg0;
            CarParKing.ServiceReference1.editParkingPlaceResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).editParkingPlace(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.editParkingPlaceResponse> CarParKing.ServiceReference1.Parking.editParkingPlaceAsync(CarParKing.ServiceReference1.editParkingPlaceRequest request) {
            return base.Channel.editParkingPlaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.editParkingPlaceResponse> editParkingPlaceAsync(CarParKing.ServiceReference1.parkingPlace arg0) {
            CarParKing.ServiceReference1.editParkingPlaceRequest inValue = new CarParKing.ServiceReference1.editParkingPlaceRequest();
            inValue.arg0 = arg0;
            return ((CarParKing.ServiceReference1.Parking)(this)).editParkingPlaceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.getTicketListResponse CarParKing.ServiceReference1.Parking.getTicketList(CarParKing.ServiceReference1.getTicketListRequest request) {
            return base.Channel.getTicketList(request);
        }
        
        public CarParKing.ServiceReference1.ticket[] getTicketList(int arg0, int arg1) {
            CarParKing.ServiceReference1.getTicketListRequest inValue = new CarParKing.ServiceReference1.getTicketListRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CarParKing.ServiceReference1.getTicketListResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).getTicketList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getTicketListResponse> CarParKing.ServiceReference1.Parking.getTicketListAsync(CarParKing.ServiceReference1.getTicketListRequest request) {
            return base.Channel.getTicketListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.getTicketListResponse> getTicketListAsync(int arg0, int arg1) {
            CarParKing.ServiceReference1.getTicketListRequest inValue = new CarParKing.ServiceReference1.getTicketListRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CarParKing.ServiceReference1.Parking)(this)).getTicketListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.editTicketResponse CarParKing.ServiceReference1.Parking.editTicket(CarParKing.ServiceReference1.editTicketRequest request) {
            return base.Channel.editTicket(request);
        }
        
        public int editTicket(int arg0, CarParKing.ServiceReference1.ticket arg1) {
            CarParKing.ServiceReference1.editTicketRequest inValue = new CarParKing.ServiceReference1.editTicketRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CarParKing.ServiceReference1.editTicketResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).editTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.editTicketResponse> CarParKing.ServiceReference1.Parking.editTicketAsync(CarParKing.ServiceReference1.editTicketRequest request) {
            return base.Channel.editTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.editTicketResponse> editTicketAsync(int arg0, CarParKing.ServiceReference1.ticket arg1) {
            CarParKing.ServiceReference1.editTicketRequest inValue = new CarParKing.ServiceReference1.editTicketRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CarParKing.ServiceReference1.Parking)(this)).editTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.createTicketResponse CarParKing.ServiceReference1.Parking.createTicket(CarParKing.ServiceReference1.createTicketRequest request) {
            return base.Channel.createTicket(request);
        }
        
        public int createTicket(int arg0, CarParKing.ServiceReference1.ticket arg1) {
            CarParKing.ServiceReference1.createTicketRequest inValue = new CarParKing.ServiceReference1.createTicketRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CarParKing.ServiceReference1.createTicketResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).createTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.createTicketResponse> CarParKing.ServiceReference1.Parking.createTicketAsync(CarParKing.ServiceReference1.createTicketRequest request) {
            return base.Channel.createTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.createTicketResponse> createTicketAsync(int arg0, CarParKing.ServiceReference1.ticket arg1) {
            CarParKing.ServiceReference1.createTicketRequest inValue = new CarParKing.ServiceReference1.createTicketRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CarParKing.ServiceReference1.Parking)(this)).createTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.getActiveTicketListResponse CarParKing.ServiceReference1.Parking.getActiveTicketList(CarParKing.ServiceReference1.getActiveTicketListRequest request) {
            return base.Channel.getActiveTicketList(request);
        }
        
        public CarParKing.ServiceReference1.ticket[] getActiveTicketList(int arg0) {
            CarParKing.ServiceReference1.getActiveTicketListRequest inValue = new CarParKing.ServiceReference1.getActiveTicketListRequest();
            inValue.arg0 = arg0;
            CarParKing.ServiceReference1.getActiveTicketListResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).getActiveTicketList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getActiveTicketListResponse> CarParKing.ServiceReference1.Parking.getActiveTicketListAsync(CarParKing.ServiceReference1.getActiveTicketListRequest request) {
            return base.Channel.getActiveTicketListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.getActiveTicketListResponse> getActiveTicketListAsync(int arg0) {
            CarParKing.ServiceReference1.getActiveTicketListRequest inValue = new CarParKing.ServiceReference1.getActiveTicketListRequest();
            inValue.arg0 = arg0;
            return ((CarParKing.ServiceReference1.Parking)(this)).getActiveTicketListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.getParkingPlaceByIdResponse CarParKing.ServiceReference1.Parking.getParkingPlaceById(CarParKing.ServiceReference1.getParkingPlaceByIdRequest request) {
            return base.Channel.getParkingPlaceById(request);
        }
        
        public CarParKing.ServiceReference1.parkingPlace getParkingPlaceById(int arg0) {
            CarParKing.ServiceReference1.getParkingPlaceByIdRequest inValue = new CarParKing.ServiceReference1.getParkingPlaceByIdRequest();
            inValue.arg0 = arg0;
            CarParKing.ServiceReference1.getParkingPlaceByIdResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).getParkingPlaceById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getParkingPlaceByIdResponse> CarParKing.ServiceReference1.Parking.getParkingPlaceByIdAsync(CarParKing.ServiceReference1.getParkingPlaceByIdRequest request) {
            return base.Channel.getParkingPlaceByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.getParkingPlaceByIdResponse> getParkingPlaceByIdAsync(int arg0) {
            CarParKing.ServiceReference1.getParkingPlaceByIdRequest inValue = new CarParKing.ServiceReference1.getParkingPlaceByIdRequest();
            inValue.arg0 = arg0;
            return ((CarParKing.ServiceReference1.Parking)(this)).getParkingPlaceByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.getParkingPlaceListResponse CarParKing.ServiceReference1.Parking.getParkingPlaceList(CarParKing.ServiceReference1.getParkingPlaceListRequest request) {
            return base.Channel.getParkingPlaceList(request);
        }
        
        public CarParKing.ServiceReference1.parkingPlace[] getParkingPlaceList() {
            CarParKing.ServiceReference1.getParkingPlaceListRequest inValue = new CarParKing.ServiceReference1.getParkingPlaceListRequest();
            CarParKing.ServiceReference1.getParkingPlaceListResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).getParkingPlaceList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getParkingPlaceListResponse> CarParKing.ServiceReference1.Parking.getParkingPlaceListAsync(CarParKing.ServiceReference1.getParkingPlaceListRequest request) {
            return base.Channel.getParkingPlaceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.getParkingPlaceListResponse> getParkingPlaceListAsync() {
            CarParKing.ServiceReference1.getParkingPlaceListRequest inValue = new CarParKing.ServiceReference1.getParkingPlaceListRequest();
            return ((CarParKing.ServiceReference1.Parking)(this)).getParkingPlaceListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.createParkingPlaceResponse CarParKing.ServiceReference1.Parking.createParkingPlace(CarParKing.ServiceReference1.createParkingPlaceRequest request) {
            return base.Channel.createParkingPlace(request);
        }
        
        public int createParkingPlace(CarParKing.ServiceReference1.parkingPlace arg0) {
            CarParKing.ServiceReference1.createParkingPlaceRequest inValue = new CarParKing.ServiceReference1.createParkingPlaceRequest();
            inValue.arg0 = arg0;
            CarParKing.ServiceReference1.createParkingPlaceResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).createParkingPlace(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.createParkingPlaceResponse> CarParKing.ServiceReference1.Parking.createParkingPlaceAsync(CarParKing.ServiceReference1.createParkingPlaceRequest request) {
            return base.Channel.createParkingPlaceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.createParkingPlaceResponse> createParkingPlaceAsync(CarParKing.ServiceReference1.parkingPlace arg0) {
            CarParKing.ServiceReference1.createParkingPlaceRequest inValue = new CarParKing.ServiceReference1.createParkingPlaceRequest();
            inValue.arg0 = arg0;
            return ((CarParKing.ServiceReference1.Parking)(this)).createParkingPlaceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarParKing.ServiceReference1.getInactiveTicketListResponse CarParKing.ServiceReference1.Parking.getInactiveTicketList(CarParKing.ServiceReference1.getInactiveTicketListRequest request) {
            return base.Channel.getInactiveTicketList(request);
        }
        
        public CarParKing.ServiceReference1.ticket[] getInactiveTicketList(int arg0) {
            CarParKing.ServiceReference1.getInactiveTicketListRequest inValue = new CarParKing.ServiceReference1.getInactiveTicketListRequest();
            inValue.arg0 = arg0;
            CarParKing.ServiceReference1.getInactiveTicketListResponse retVal = ((CarParKing.ServiceReference1.Parking)(this)).getInactiveTicketList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarParKing.ServiceReference1.getInactiveTicketListResponse> CarParKing.ServiceReference1.Parking.getInactiveTicketListAsync(CarParKing.ServiceReference1.getInactiveTicketListRequest request) {
            return base.Channel.getInactiveTicketListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarParKing.ServiceReference1.getInactiveTicketListResponse> getInactiveTicketListAsync(int arg0) {
            CarParKing.ServiceReference1.getInactiveTicketListRequest inValue = new CarParKing.ServiceReference1.getInactiveTicketListRequest();
            inValue.arg0 = arg0;
            return ((CarParKing.ServiceReference1.Parking)(this)).getInactiveTicketListAsync(inValue);
        }
    }
}
